#### Bookkeeping

In [14]:
# Adding a folder full of useful code into the sys.path
import os
import sys
base_path = os.getcwd()
lib_path = os.path.join(base_path,"Useful_Code")
sys.path.append(lib_path)
print base_path
print lib_path

# Relevant imports
import numpy as np
import pandas as pd
import sklearn
from sklearn import datasets
import scipy
import matplotlib.pyplot as plt
import Swiss

C:\Users\Juan\Machine Learning\Week 3
C:\Users\Juan\Machine Learning\Week 3\Useful_Code

Hi this notebook is heavily adopted from:
"Python Machine Learning 2nd Edition by Sebastian Raschka, Packt Publishing Ltd. 2017

Code Repository: https://github.com/rasbt/python-machine-learning-book-2nd-edition

Code License: MIT License"
by Juan Bohorquez, no licenses just me.

Additional resources:

# Dealing With Missing Data

Sometimes your dataset will have holes in it. This is obviously bad. Here we'll explore a few methods that are useful when dealing with broken data.

## But first a word about dataframes and csv files

Throughout the book Raschka uses dataframes as the standard datastructure. Here he presents two ways we might create a dataframe:
1. Importing a .csv, this is convenient as a good fraction of datasets are available originally as .csvs
2. Building a dataframe object using a constructor
I'll show examples of doing both

### 1. Building a dataframe from a .csv file.
I'll use Greg's FIFA data file as an example of how pandas imports .csvs

In [15]:
dfcsv = pd.read_csv("FIFA_Data\\FIFA_WorkRate_Analysis_195.csv",sep="\t")
dfcsv

    Attacking_Work_Rate  Marking  Aggression  Reactions  Speed  Stamina
0                  High       22          63         96     92       92
1                Medium       13          48         95     87       74
2                  High       21          56         88     90       79
3                  High       30          78         93     77       89
4                Medium       10          29         85     61       44
5                Medium       13          38         88     56       25
6                  High       25          80         88     82       79
7                  High       51          65         87     95       78
8                Medium       15          84         85     74       75
9                Medium       11          23         81     52       38
10               Medium       90          82         84     81       75
11                 High       25          54         85     87       77
12                 High       66          62         88     71       83
13               Medium       22          48         87     68       68
14                 High       12          50         86     81       73
15                 High       90          77         84     76       74
16                 High       85          84         82     78       84
17                 High       13          57         88     86       74
18                 High       68          72         86     79       91
19                 High       23          69         90     86       75
20                 High       30          68         88     78       85
21               Medium       30          49         87     91       73
22                 High       30          80         87     84       85
23               Medium       63          60         85     37       78
24               Medium       87          86         85     67       69
25                 High       85          66         85     65       66
26               Medium       12          31         84     63       41
27               Medium       86          58         91     67       79
28               Medium       88          94         84     75       64
29               Medium       11          17         86     50       32
..                  ...      ...         ...        ...    ...      ...
165              Medium       79          83         82     80       79
166                High       81          83         81     66       79
167              Medium       13          42         79     58       36
168                High       82          73         82     73       62
169              Medium       15          60         81     82       70
170              Medium       84          84         85     54       69
171              Medium       84          74         77     54       75
172                High       35          33         77     78       75
173              Medium       83          78         84     66       68
174              Medium       81          83         81     72       73
175                High       81          74         80     75       86
176              Medium       14          33         78     60       35
177              Medium       58          52         84     68       76
178                High       33          67         75     77       71
179              Medium       14          28         77     60       28
180                High       83          78         82     87       89
181              Medium       32          65         76     73       63
182                High       15          62         80     79       75
183                High       78          84         80     83       88
184              Medium       48          81         83     73       84
185              Medium       75          84         80     69       79
186              Medium       12          32         82     63       34
187                High       10          62         78     83       68
188              Medium       30          45         78     78       74
189              Medium       46          58         83     77       80
190                High       34          88         84     76       91
191              Medium       82          70         81     78       60
192                High       35          59         81     91       80
193                High       57          84         83     76       88
194              Medium        9          27         85     62       38

[195 rows x 6 columns]

### 2. Building a dataframe from an existing dataset
Here I'll use truncated data from the iris dataset in sklearn.
the DataFrame constructor allows you to input data in a variety of different ways. Here I just demonstrate how to do this using a 2D numpy array of data along with an array of feature names.

More info on the DataFrame class, and some examples, can be found here:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [22]:
iris = datasets.load_iris()
iris_data = iris['data']
df = pd.DataFrame(data = data[:5], columns = iris['feature_names'])
df

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                NaN               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                NaN               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

### Writing data to a .csv
Here I'll write to a .csv with tab separators

Further documentation and examples are available here:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html

In [23]:
data_path = os.path.join(base_path,"Iris_Data\iris.csv")
df.to_csv(path_or_buf=data_path,sep='\t')

## Now lets poke some holes in the data

I've made a file called Swiss with one method (so far) that randomly deletes entries in a 2D numpy array. Docstring:  

Swiss.holes(): a function that, pseudo-randomly, pokes holes into a dataset.  
Parameters:  
* data - a 2D numpy array of data in the form of Scikit-learn datasets. ie: data.size = ["Number of Samples","Number of Features"]  
* ratio - desired ratio of deleted datapoints to untouched datapoints  
* seed -  a seed to be fed into the random number generator for repeatability  

Return:  
* data - the input numpy array with random entries removed

In [24]:
holy_data = Swiss.holes(iris_data,ratio = 0.1,seed = 599594)
holy_df = pd.DataFrame(data = holy_data,columns = iris['feature_names'])
holy_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                NaN               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                NaN               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  NaN               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                NaN               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               NaN                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               NaN                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 NaN               3.4                1.9               0.2
25                 5.0               3.0                NaN               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 NaN               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               NaN
121                5.6               2.8                4.9               NaN
122                NaN               NaN                6.7               2.0
123                NaN               2.7                4.9               1.8
124                NaN               3.3                5.7               2.1
125                7.2               3.2                NaN               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               NaN                5.6               2.1
129                NaN               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                NaN               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                NaN               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               NaN                5.0               1.9
147                6.5               3.0                NaN               2.0
148                6.2               3.4                5.4               2.3
149                5.9               NaN                5.1               1.8

[150 rows x 4 columns]

Now we have data with holes in it. We can't exactly plug this data into a ML algorithm so we'll have to get rid of the holes in our data.
Raschka presents two methods for dealing with problem data:

## Method 1: Deleting problem data
pandas has methods built in that indicate if a particular index contains Nan, and then has methods which can be used to delete the identified rows or columns, here are a bunch of examples of how you might delete problem data.

Deleting problem data is often the best way to go if you can afford to lose some data. Imputing data can introduce noise into your model and reduce its efficacy.

In [26]:
# removing rows that contain missing values
drop_rows = holy_df.dropna(axis=0)
# removing columns that contain missing values
drop_columns = holy_df.dropna(axis=1)
# drop rows where all columns are NaN
no_empty = holy_df.dropna(how='all')
# drop rows that have less than 3 real values
thresh = holy_df.dropna(thresh=4)
# only drop rows where NaN appears in a given column
# colum values = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)']
given_column = holy_df.dropna(subset = ['sepal length (cm)'])

#Uncomment lines below to check out datasets treated in a given way

new_iris = drop_rows
#new_iris = drop_columns
#new_iris = no_empty
#new_iris = thresh
#new_iris = given_column

new_iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                  4.9               3.0                1.4               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
30                 4.8               3.1                1.6               0.2
31                 5.4               3.4                1.5               0.4
33                 5.5               4.2                1.4               0.2
34                 4.9               3.1                1.5               0.1
35                 5.0               3.2                1.2               0.2
36                 5.5               3.5                1.3               0.2
39                 5.1               3.4                1.5               0.2
42                 4.4               3.2                1.3               0.2
43                 5.0               3.5                1.6               0.6
..                 ...               ...                ...               ...
100                6.3               3.3                6.0               2.5
101                5.8               2.7                5.1               1.9
102                7.1               3.0                5.9               2.1
103                6.3               2.9                5.6               1.8
105                7.6               3.0                6.6               2.1
107                7.3               2.9                6.3               1.8
108                6.7               2.5                5.8               1.8
109                7.2               3.6                6.1               2.5
110                6.5               3.2                5.1               2.0
111                6.4               2.7                5.3               1.9
114                5.8               2.8                5.1               2.4
116                6.5               3.0                5.5               1.8
119                6.0               2.2                5.0               1.5
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
148                6.2               3.4                5.4               2.3

[99 rows x 4 columns]

Above we show the new dataframe after removing all samples with missing data. Note that with a roughly 10% data error rate we lose 51 out of 150 samples, thats about 33%!


## Method 2: Imputing missing values
deleting data has obvious drawbacks. If you delete too much data might not have enough training data, and deleting features might make you lose relevant fitting data.
Another method is to fill in these gaps. Commonly by taking the mean value of the data in that column.

The book details using the built in Imputer class as we do below. Common implementations use the mean value for a feature with missing data to fill in the gaps. Other strategies, such as regression are also viable but can be computationally costly. Below we implement mean imputing.

In [31]:
from sklearn.preprocessing import Imputer

imr = Imputer(missing_values='NaN', strategy = 'mean', axis = 0)
imr = imr.fit(holy_df.values)
imputed_iris = imr.transform(holy_df.values)
imputed_iris
patchy_iris = pd.DataFrame(data = imputed_iris,columns = iris['feature_names'])
patchy_iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             5.100000           3.50000           3.766418          0.200000
1             4.900000           3.00000           1.400000          0.200000
2             4.700000           3.20000           3.766418          0.200000
3             4.600000           3.10000           1.500000          0.200000
4             5.000000           3.60000           1.400000          0.200000
5             5.800752           3.90000           1.700000          0.400000
6             4.600000           3.40000           1.400000          0.300000
7             5.000000           3.40000           1.500000          0.200000
8             4.400000           2.90000           1.400000          0.200000
9             4.900000           3.10000           1.500000          0.100000
10            5.400000           3.70000           1.500000          0.200000
11            4.800000           3.40000           1.600000          0.200000
12            4.800000           3.00000           3.766418          0.100000
13            4.300000           3.00000           1.100000          0.100000
14            5.800000           4.00000           1.200000          0.200000
15            5.700000           3.05597           1.500000          0.400000
16            5.400000           3.90000           1.300000          0.400000
17            5.100000           3.50000           1.400000          0.300000
18            5.700000           3.80000           1.700000          0.300000
19            5.100000           3.05597           1.500000          0.300000
20            5.400000           3.40000           1.700000          0.200000
21            5.100000           3.70000           1.500000          0.400000
22            4.600000           3.60000           1.000000          0.200000
23            5.100000           3.30000           1.700000          0.500000
24            5.800752           3.40000           1.900000          0.200000
25            5.000000           3.00000           3.766418          0.200000
26            5.000000           3.40000           1.600000          0.400000
27            5.200000           3.50000           1.500000          0.200000
28            5.200000           3.40000           1.400000          0.200000
29            5.800752           3.20000           1.600000          0.200000
..                 ...               ...                ...               ...
120           6.900000           3.20000           5.700000          1.201429
121           5.600000           2.80000           4.900000          1.201429
122           5.800752           3.05597           6.700000          2.000000
123           5.800752           2.70000           4.900000          1.800000
124           5.800752           3.30000           5.700000          2.100000
125           7.200000           3.20000           3.766418          1.800000
126           6.200000           2.80000           4.800000          1.800000
127           6.100000           3.00000           4.900000          1.800000
128           6.400000           3.05597           5.600000          2.100000
129           5.800752           3.00000           5.800000          1.600000
130           7.400000           2.80000           6.100000          1.900000
131           7.900000           3.80000           6.400000          2.000000
132           6.400000           2.80000           5.600000          2.200000
133           5.800752           2.80000           5.100000          1.500000
134           6.100000           2.60000           5.600000          1.400000
135           7.700000           3.00000           6.100000          2.300000
136           6.300000           3.40000           5.600000          2.400000
137           6.400000           3.10000           5.500000          1.800000
138           6.000000           3.00000           4.800000          1.800000
139           6.900000           3.10000           5.400000          2.100000
140           6.700000           3.10000           5.600000          2.400000
141           5.800752           3.10000           5.100000          2.300000
142           5.800000           2.70000           5.100000          1.900000
143           6.800000           3.20000           5.900000          2.300000
144           6.700000           3.30000           5.700000          2.500000
145           6.700000           3.00000           5.200000          2.300000
146           6.300000           3.05597           5.000000          1.900000
147           6.500000           3.00000           3.766418          2.000000
148           6.200000           3.40000           5.400000          2.300000
149           5.900000           3.05597           5.100000          1.800000

[150 rows x 4 columns]